// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIaHSVDpcwLoVkKM32owfZLXPyfbHDP0w',
    appId: '1:567566391464:web:6dff44b8be903e21dcca9d',
    messagingSenderId: '567566391464',
    projectId: 'flutterquize',
    authDomain: 'flutterquize.firebaseapp.com',
    storageBucket: 'flutterquize.appspot.com',
    measurementId: 'G-MHHPP1HCWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbjOnrSigs-silQe6XjzD7I56_R-E1OfM',
    appId: '1:567566391464:android:b39554f92f16c360dcca9d',
    messagingSenderId: '567566391464',
    projectId: 'flutterquize',
    storageBucket: 'flutterquize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ4mKTywFIoR6J42fjKV6TPNNaJWGaSbI',
    appId: '1:567566391464:ios:d80fb57fc7cb5442dcca9d',
    messagingSenderId: '567566391464',
    projectId: 'flutterquize',
    storageBucket: 'flutterquize.appspot.com',
    androidClientId: '567566391464-2610qn8s1mghu5mboj8eje6sru63bgs4.apps.googleusercontent.com',
    iosClientId: '567566391464-lim2qdskldtt1frkf0i2kebt82rjd097.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ4mKTywFIoR6J42fjKV6TPNNaJWGaSbI',
    appId: '1:567566391464:ios:d80fb57fc7cb5442dcca9d',
    messagingSenderId: '567566391464',
    projectId: 'flutterquize',
    storageBucket: 'flutterquize.appspot.com',
    androidClientId: '567566391464-2610qn8s1mghu5mboj8eje6sru63bgs4.apps.googleusercontent.com',
    iosClientId: '567566391464-lim2qdskldtt1frkf0i2kebt82rjd097.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineShop',
  );
}
